site_name: Katamari Damacy REROLL Speedrun Notes
site_url: https://shookietea.github.io/reroll-notes
repo_url: https://github.com/shookieTea/reroll-notes
edit_uri: blob/main/docs/
site_author: shookieTea
site_description: Speedrunning notes for Katamari Damacy REROLL

nav:
  - 'Home': 'index.md'
  - 'Resources':
      - 'resources.md'
      - 'Overworld Map.md'
  - 'Levels':
      - 'MAS1.md'
      - 'MAS2.md'
      - 'Cancer.md'
      - 'MAS3.md'
      - 'MAS4.md'
      - 'Cygnus.md'
      - 'MAS5.md'
      - 'Corona Borealis.md'
      - 'MAS6.md'
      - 'Ursa Major.md'
      - 'Gemini.md'
      - 'Pisces.md'
      - 'MAS7.md'
      - 'Taurus.md'
      - 'MAS8.md'
      - 'Virgo.md'
      - 'MAS9.md'
      - 'North Star.md'
      - 'Make the moon': 'MOON.md'

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
